#!/usr/bin/python
# -*- coding: utf-8  -*-

import sys

intab = u'ΆΈΉΊΌΎΏΪ'
outab = u'ΑΕΗΙΟΥΩΙ'
trtab = dict((ord(a), b) for a, b in zip(intab, outab))

fin = open(sys.argv[1],"r")
fout = open(sys.argv[2],"w")

for line in fin:
	uline = line.decode('utf-8').upper()
	uline = uline.translate(trtab)
	eline = uline.encode('utf-8')
	fout.write(eline)
