#!/usr/bin/python
# -*- coding: utf-8  -*-

import sys
import codecs

intab = u'ΆΈΉΊΌΎΏΪ'
outab = u'ΑΕΗΙΟΥΩΙ'
trtab = dict((ord(a), b) for a, b in zip(intab, outab))

fin = codecs.open(sys.argv[1],"r","utf-8")
fout = codecs.open(sys.argv[2],"w","utf-8")

for line in fin:
	nline = line.upper()
	nline = nline.translate(trtab)
	fout.write(nline)
